### ISSUE TITLE
Grep not working when there is a filename same as search input

### ISSUE THREAD

**Issue by iris-garcia** [minad/affe#13]
Still not sure if this happens always but today I realized I was getting weird results:

![image](https://user-images.githubusercontent.com/3024945/120519342-c9231480-c3d2-11eb-8524-3d3f8e5211a4.png)

To reproduce it, just create a file that matches the input text when running `affe-grep`, in my case I created a file `file.yaml` with content having the word `file` so I expect `affe-grep` to filter just the lines matching it.

My `file.yaml` content is:
```
---
- hosts: webservers

  vars:
    http_port: 80
    max_clients: 200

  remote_user: root

  tasks:
  - name: ensure apache is at the latest version
    yum:
      name: httpd
      state: latest

  - name: write the apache config file
    template:
      src: /srv/httpd.j2
      dest: /etc/httpd.conf
    notify:
    - restart apache

  - name: ensure apache is running file
    service:
      name: httpd
      state: started

  handlers:
    - name: restart apache file
      service:
        name: httpd
        state: restarted
```

Apparently it matches the whole content of the file just because the filename matches.
